### ISSUE TITLE
Calculate City Climate Variables

### ISSUE THREAD

**Issue by justinperline** [justinperline/samegrassbutgreener#9]
Want to know a few different climate traits about each city:

- Winter temperature
- Summer temperature
- Seasonality
- Precipitation
- Humidity

**Comment by justin-perline** [comment]
I attempted to use a spatial raster to match a grid of climate variables to each US county but ran into issues because I wasn't able to troubleshoot why certain counties were not appearing in the end-result. I need to do more research into the packages I used prior to going further. I'll note that two of the main packages used here are development versions maintained by NOAA employees rather than full CRAN packages.

Instead, I used pre-allocated county climate datasets downloaded from NOAA's website to match counties to census-designated places. Winter temperature, summer temperature, and precipitation were all able to be downloaded and matched.

Code: https://github.com/justinperline/samegrassbutgreener/blob/main/code/climate.R

**Comment by justinperline** [comment]
I attempted to use a spatial raster to match a grid of climate variables to each US county but ran into issues because I wasn't able to troubleshoot why certain counties were not appearing in the end-result. I need to do more research into the packages I used prior to going further. I'll note that two of the main packages used here are development versions maintained by NOAA employees rather than full CRAN packages.

Instead, I used pre-allocated county climate datasets downloaded from NOAA's website to match counties to census-designated places. Winter temperature, summer temperature, and precipitation were all able to be downloaded and matched.

Code: https://github.com/justinperline/samegrassbutgreener/blob/main/code/climate.R
